# Generated by Django 3.1.7 on 2021-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerson', '0002_auto_20210320_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
